// <auto-generated />
namespace MiniStackOverflow.DataDeployed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Quest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Quest));
        
        string IMigrationMetadata.Id
        {
            get { return "201502240250324_Quest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
